### ISSUE TITLE
Helminth Hatchery magma keeps destroying Spider Drones.

### ISSUE THREAD

**Issue by Aaron00000** [viliger2/RoR2_EnemiesReturns#11]
Spider bots will more often than not be cooked by the magma on the lower levels, and will almost immediately be destroyed again after being repurchased while within said magma. Would recommend adding either full immunity to magma or a grace period of invincibility after repurchasing.

**Comment by viliger2** [comment]
With https://github.com/viliger2/RoR2_EnemiesReturns/commit/0f8de7935a7617a312b23bcef2908eda29f789a3 I've marked drone spiders as immune to lava.
Sadly lava is made in such a way that there is no real way (without writing On or IL hooks ofc) to somewhat limit lava damage, Gearbox just hardcoded that players take 10% of their hp dealt each tick, bosses take 1% and monsters take 2%. Drones count as players since they are on player team.

**Comment by viliger2** [comment]
I've discovered that lava deals damage on a timer per body instead of global static timer, so with https://github.com/viliger2/RoR2_EnemiesReturns/commit/53060db4e3e4e38ce25734d20ab9e7bf918ed18c instead of full lava immunity I've decided to put lava damage on 1 second cooldown for drone mechanical spiders. Enemy spiders behavior is unchanged.
