### ISSUE TITLE
Mech Spider NRE

### ISSUE THREAD

**Issue by goldenguy00** [viliger2/RoR2_EnemiesReturns#13]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EnemiesReturns.ModdedEntityStates.MechanicalSpider.DoubleShot.Fire.FixedUpdate () (at <bbaa319a11e94a48a75227c901967531>:IL_00A1)
RoR2.EntityStateMachine.ManagedFixedUpdate (System.Single deltaTime) (at <d40ed1fc32a5436f8b992e36da98a05d>:IL_001D)
RoR2.EntityStateMachine.FixedUpdate () (at <d40ed1fc32a5436f8b992e36da98a05d>:IL_0006)

just keeps getting spammed, probably died and cant exit the state cuz of nre

**Comment by goldenguy00** [comment]
ye its intangible body keeps on walkin 
![{8FBD298C-390F-4465-8165-3E1FAE089CCB}](https://github.com/user-attachments/assets/6f515133-c344-4c95-8b30-7dc590ae49bc)

**Comment by viliger2** [comment]
Can you send the full log? I've added a nullcheck to the problematic line of code, but still, it should've left the state when it died. Instead it is stuck in that state, trying to fire, despite the fact that its master is long gone.

**Comment by goldenguy00** [comment]
[zipped_log.zip](https://github.com/user-attachments/files/17792341/zipped_log.zip)

**Comment by viliger2** [comment]
My only guess is that spider died and somehow run state switch code on the same logical frame and instead of dying it is now stuck running around trying to shoot.
With https://github.com/viliger2/RoR2_EnemiesReturns/commit/642e1bda7a73d3bdbd23b038e9a6a196400f206d I've added nullchecks to the state, but that doesn't fix the issue of masterless spider running around.

**Comment by goldenguy00** [comment]
sick
